# Generated by Django 4.2.7 on 2025-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_conversation_bot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
